# 监听本地的端口
listen: :8086

# 使用redis来存放access_token
redis:
  host: 127.0.0.1:6379

# 微信公众号相关配置
officialAccountConfig:
  appID: wxd6f8ae8d044d5d88
  appSecret: 4f860c470a0badd564b5d31f19f498da
  token: t123456


 